language: java
dist: bionic
git:
  depth: false
  quiet: true
# Only build master branch
branches:
  only:
  - master
before_install:
- sudo apt-get install ant-optional
install: ant download-deps
notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false 
# Run SonarQube on code
addons:
  sonarcloud:
    organization: "sylvainhalle-github"
    token:
      secure: c11f78b32f6c5a83c760c5b6d6ea388e166b07f7 # encrypted value of your token
script:
  - ant test
  - sonar-scanner
