language: java
dist: bionic
git:
  depth: false
  quiet: true
branches:
  only:
  - master
addons:
  sonarcloud:
    organization: "sylvainhalle-github"
    token:
      secure: IV+3495+DLofyAub7uFMfqL3k9yPUeVM8BkjNlezyDS1qbw0so5XVhEfCkZxFj97cLjzlWLS7kNPvg1S6gHDPhqakRBKRAkasr+qxaVAHZs9++Gr3/Mg9OoUiSixa/H/Uhbh1iSXHiflyscBizxkolUr4kopQzG8Q3YPbYAjB2R5aIN8FKqegJPULAPdutpug6NwccTaO3sScRx4OotweuC5zMq0KsCULJbaXrLue3+9BxqT86dYauUboSHdXFFHC5neoadOEyVIMqECYyb1tP1WBVnA78vrxt/XDdF67ZSmfbSxLiuFLI1xhVrwFKq1vtAZsYXEAOTJ1UUFzqz4nNvU4tkX4IUDoJhRtv5ltoTML7hDTUNBfcUMxKjGE00DMJodeJZF8IH9T7AaQ8fjqO8m1DOzZdEnh9t9hHgrb+oMJ/Hm0Ro05jC0CjX1RmmJZr00Ay+GCOTm+dSJEYyhjIPUrRZsG/xq9X1+QHTo5xZKvZsYTDxynK4USZVu4x/NNitvuk4MJW0C0n2xmCQkGrEfU+YsNH0PAq9uyNnDJgqSXY1cgd/ZXYWA1hd8EasKwoVUIPHKl7CPqmtSw9SZYrit/nOahPCMkr0Cr1ayrn1PUBRs3o8vATUbCEeIydTfCC5YXG1X6H1wiA3pvUujwxnzwXhN8631xbaCis7YC00=
before_install:
- sudo apt-get install ant-optional
install: ant download-deps
notifications:
  email: false
script:
- ant test
- sonar-scanner
deploy:
  provider: releases
  api_key:
    secure: "W9vzRIQJUHT+w2vqndmPRr1qIrzg6Do/9+ujNwavtEn7a8cJrFWHdyKg129tuQuSlS/UcEnMlfG5PWvkL96QLnpitySjOwKw0je00iykPXN1LHuHxDsmmAnnIq7Q4ozZYlIhnCxpf+4kDXpB6Z8mvpSxfO+aGKUTMYpvf1DrLq/0xCAdHQxqVVl1SxXlaEX5Elr9r4KzqvsPfxrFi8nHbCsdAfzr82kCXSfa1Ayuzpv4iatFeMP50cu+gYs8zAMD/OSamt0IG+COiBhUPvaS2M8GFewkEFpuqx+X4jyKr7+3WePHRqf1YUtQRy7X65FvhpxqYH9YyduMvE7zWWEVnSPaLNtkLZQsSGR6bzRpcOiJBvBFEBAhGMuCgGCfRM+pOAtD9sb58bzqFdJ4EPSWmPz/1IZOeBhagLY4PpFKVvBrOfBTILACsHVS2aN5D9BVwaFJV7tI7o3tIOJZ+EGWyf7b7NjWHrox6s/uaC1G2zwvr+aWPZkeM9RI0aOi+ulBsRLhMxz46ZnTcysCyR1MqaM2z/CRPxchzZ04PGr2HOh2ij2yi5FHVhiD3X2qfrCgImGbVn9ycW9Xyo1RVj9CdCBpKgxBRdk8B3/ZQnSJFIcvRpxfFoVKyJS0VUgRUfu3r8GIS7X9Tm3Ov0NpH8YHpXq9mapxP+reSrYF6kSKegg="
  file: 'textidote.jar'
  skip_cleanup: true
  on:
    tags